services:
  n8n:
    environment:
      - N8N_HOST=n8n.speedandfunction.com
      - N8N_PROTOCOL=https
      - N8N_SSL_KEY=/home/node/certs/n8n.privkey.pem
      - N8N_SSL_CERT=/home/node/certs/n8n.fullchain.pem
      - N8N_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID is required}
      - N8N_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET is required}
      - N8N_GOOGLE_CALLBACK_URL=${N8N_GOOGLE_CALLBACK_URL:?N8N_GOOGLE_CALLBACK_URL is required}
      - N8N_GOOGLE_SCOPES=email profile
      - N8N_AUTH_TYPE=google
    volumes:
      - /etc/letsencrypt/live/n8n.speedandfunction.com/fullchain.pem:/home/node/certs/n8n.fullchain.pem:ro
      - /etc/letsencrypt/live/n8n.speedandfunction.com/privkey.pem:/home/node/certs/n8n.privkey.pem:ro

  oauth2-proxy:
    container_name: temporal-oauth-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.0
    restart: unless-stopped
    depends_on:
      - temporal-ui
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      # Google provider settings
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_CLIENT_ID=${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID is required}
      - OAUTH2_PROXY_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET is required}
      
      # Email validation settings
      - OAUTH2_PROXY_EMAIL_DOMAINS=speedandfunction.com
      
      # Required settings
      - OAUTH2_PROXY_COOKIE_DOMAINS=.temporal.speedandfunction.com
      - OAUTH2_PROXY_WHITELIST_DOMAINS=.temporal.speedandfunction.com
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:8080
      - OAUTH2_PROXY_UPSTREAMS=http://temporal-ui:8080
      - OAUTH2_PROXY_REDIRECT_URL=${OAUTH2_PROXY_REDIRECT_URL:-https://temporal.speedandfunction.com/oauth2/callback}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET:?OAUTH2_PROXY_COOKIE_SECRET is required}
      
      # Cookie settings
      - OAUTH2_PROXY_COOKIE_NAME=_oauth2_proxy
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_HTTPONLY=true
      - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      - OAUTH2_PROXY_COOKIE_REFRESH=1h
      - OAUTH2_PROXY_COOKIE_EXPIRE=168h
      
      # CSRF protection settings
      - OAUTH2_PROXY_CSRF_COOKIE_NAME=_oauth2_proxy_csrf
      - OAUTH2_PROXY_CSRF_COOKIE_SECURE=true
      - OAUTH2_PROXY_CSRF_COOKIE_DOMAIN=.temporal.speedandfunction.com
      - OAUTH2_PROXY_CSRF_COOKIE_HTTPONLY=true
      - OAUTH2_PROXY_CSRF_COOKIE_SAMESITE=lax
      
      # SSL certificate settings
      - OAUTH2_PROXY_SSL_CERT=/home/node/certs/temporal.fullchain.pem
      - OAUTH2_PROXY_SSL_KEY=/home/node/certs/temporal.privkey.pem
      
      # Debug settings
      - OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR=true
      
      # Logout settings
      - OAUTH2_PROXY_SIGN_OUT_URL=https://temporal.speedandfunction.com/oauth2/sign_out
    volumes:
      - /etc/letsencrypt/live/temporal.speedandfunction.com/fullchain.pem:/home/node/certs/temporal.fullchain.pem:ro
      - /etc/letsencrypt/live/temporal.speedandfunction.com/privkey.pem:/home/node/certs/temporal.privkey.pem:ro
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "https://localhost:443/oauth2/health", "--no-check-certificate"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

volumes:
  n8n_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/n8n
  opensearch-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/opensearch
  postgresql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/postgresql