volumes:
  n8n_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/n8n
  opensearch-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/opensearch
  postgresql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/postgresql
